### PR TITLE
Feat/vexflow4

### PR DESCRIPTION
**Pull request by rvilarl**
Merged with develop

### CODE REVIEW

**Review by sschmidTU — APPROVED** [review]
Looks mostly good! Some layout improvements, e.g. a final half note rest in a 4/4 measure happens much further left in the measure, about at the half point, and takes more space.
(black is the current version)
image
image

Though sometimes the notes stop a bit too far from the measure end for my taste (too much end measure padding), e.g. here:
image

@rvilarl 
There's one new error: In some tab scores, we get a TickMismatch error.
I debugged into it with `BrookeWestSample.mxl`, and it was one voice with a tick of 1/16384 or something with totalticks 0/1.
[BrookeWestSample.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9648895/BrookeWestSample.zip)

It seems to me this check is unnecessary and should give a warning instead of throwing an error:
https://github.com/0xfe/vexflow/blob/bded017767e6b0142b5a8e37f1dda231bbaf2f59/src/formatter.ts#L566

It also seems like this error comes from within Vexflow's calculations and there isn't much the user of vexflow can do about it.
Disabling this error throwing, the score renders normally.

But we can merge for now and deal with this afterwards.

**Comment by sschmidTU** [comment]
I was wondering whether I should squash the commits or not, but decided to squash in the end, as it's 71 commits from develop that have little extra information and would just fill the commit log.
Here's the diff of the critical fix commit adadff2b87a5a068255eda6cbea8553eef7ea3e5:

```diff
git show adadff2b87a5a068255eda6cbea8553eef7ea3e5                  
commit adadff2b87a5a068255eda6cbea8553eef7ea3e5
Author: Rodrigo Vilar <rvilarl@gmail.com>
Date:   Fri Sep 23 22:07:47 2022 +0200

    Fix merge

diff --git a/src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts b/src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
index 85961c2d..07d721ba 100644
--- a/src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
+++ b/src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
@@ -30,6 +30,7 @@ import { TabNote } from "../../VoiceData/TabNote";
 import { PlacementEnum } from "../../VoiceData/Expressions/AbstractExpression";
 import { GraphicalStaffEntry } from "../GraphicalStaffEntry";
 import { Slur } from "../../VoiceData/Expressions/ContinuousExpressions/Slur";
+import { Dot } from "vexflow";

 /**
  * Helper class, which contains static methods which actually convert
diff --git a/src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts b/src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
index ae7e5469..b3ed0f93 100644
--- a/src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
+++ b/src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
@@ -1165,7 +1165,7 @@ export class VexFlowMeasure extends GraphicalMeasure {
                     }
                     const graceNoteGroup: VF.GraceNoteGroup = new VF.GraceNoteGroup(graceNotes, graceSlur);
                     (graceNoteGroup as any).spacing = this.rules.GraceNoteGroupXMargin * 10;
-                    ((gve as VexFlowVoiceEntry).vfStaveNote as StaveNote).addModifier(0, graceNoteGroup);
+                    ((gve as VexFlowVoiceEntry).vfStaveNote as StaveNote).addModifier(graceNoteGroup, 0);
                     graceGVoiceEntriesBefore = [];
                 }
             }
@@ -1204,7 +1204,7 @@ export class VexFlowMeasure extends GraphicalMeasure {
             this.vfVoices[voice.VoiceId] = new VF.Voice({
                         beat_value: this.parentSourceMeasure.ActiveTimeSignature.Denominator,
                         num_beats: this.parentSourceMeasure.ActiveTimeSignature.Numerator,
-                        resolution: VF.RESOLUTION,
+                        resolution: VF.Flow.RESOLUTION,
                     }).setMode(VF.Voice.Mode.SOFT);

             const restFilledEntries: GraphicalVoiceEntry[] = this.getRestFilledVexFlowStaveNotesPerVoice(voice);
```

**Comment by rvilarl** [comment]
Happy to see that is getting better! I will look into the check you mentioned.

**Comment by AaronDavidNewman** [comment]
>> It also seems like this error comes from within Vexflow's calculations and there isn't much the user of vexflow can do about it.

Setting score mode= SOFT doesn't do it?  I don't see an error in Smoosic rendering this xml.

**Pull request merged**
