### PR TITLE
vexflow beta

### PR DESCRIPTION
**Pull request by rvilarl**
Update to use beta version.

### CODE REVIEW

**Comment by rvilarl** [comment]
There should be some fixes :)
test_staverepetitions_coda_etc musicxml_1

**Comment by rvilarl** [comment]
@sschmidTU running `npm run test:visual:build` I get the same errors that you reference in #1139 not only in current but also in blessed. How do you get the blessed images right?

**Comment by sschmidTU** [comment]
@rvilarl To get blessed images, run `git checkout develop` and `npm run generate:blessed`.

New problem: when I freshly checkout the feat/vexflow4 branch on Windows without having npm installed on develop before, I get webpack build errors:
`Error("Cannot find module 'vexflow'")`
`Module not found: Error: Can't resolve 'vexflow' in 'C:\Users\simon\osmd\vf4-osmd\src\MusicalScore\Graphical\VexFlow'`
16 times.
`webpack 5.69.1 compiled with 16 errors`

npm run build still works on the folder I copied from my old machine, same git state.

**Comment by sschmidTU** [comment]
I'll check out the beta later and see what has been fixed from this list!
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1139#issuecomment-1032827943

**Comment by sschmidTU** [comment]
@rvilarl you probably forgot to run `npm install` again after checking out develop to generate the blessed images. If you install vexflow 4, then checkout develop without running npm install, you're still running vexflow 4.

**Comment by rvilarl** [comment]
> New problem: when I freshly checkout the feat/vexflow4 branch on Windows without having npm installed on develop before, I get webpack build errors: `Error("Cannot find module 'vexflow'")` `Module not found: Error: Can't resolve 'vexflow' in 'C:\Users\simon\osmd\vf4-osmd\src\MusicalScore\Graphical\VexFlow'` 16 times. `webpack 5.69.1 compiled with 16 errors`
> 
> This also happens with the new beta and the latest webpack. Is there maybe a slight error in the module configuration?
> 

I have had this problem with the new beta 1. I reported that to @ronyeh
@0xfe fyi

**Comment by sschmidTU** [comment]
@rvilarl Nice! I'll look into it and merge soon.
It would be nice if the build wouldn't fail though, but I can wait for ronyeh's fix.

**Comment by rvilarl** [comment]
@sschmidTU I fixed the flat issue in the last commit. It was not a vexflow issue.
test_drum_tuplet_flat_beams_Siebener_Endstreich_testFlam musicxml_1_Current

**Comment by rvilarl** [comment]
@sschmidTU let me know if there is any show stopper to finally merge :)

**Comment by rvilarl** [comment]
@sschmidTU perhaps it would make sense to do a OSMD beta like in vexflow so that some people can start testing it.

**Comment by rvilarl** [comment]
@infojunkie would you also like to see a beta using vexflow 4?

**Comment by infojunkie** [comment]
> @infojunkie would you also like to see a beta using vexflow 4?

Yes, that would be great, because accidentals support is much better in vexflow 4.

**Comment by rvilarl** [comment]
> @sschmidTU perhaps it would make sense to do a OSMD beta like in vexflow so that some people can start testing it.

@sschmidTU what are your thoughts?

**Comment by sschmidTU** [comment]
about the new beta diffs:
@rvilarl this new beta loses the y-alignment of downbows in our OSMD Function Test - All. Any reasons/thoughts?
image

before:
image

after:
image

The fixes for extra clefs and beams are very nice!

About the beta, we can do that, though that's also time that could be spent on other things, and I'm not sure we want to make 10 betas for vexflow 4 with each update. Let's see. You should be able to just build it yourself from this branch.

**Comment by sschmidTU** [comment]
about the new beta diffs:
@rvilarl[](https://user-images.githubusercontent.com/33069673/157725161-b5a5ee60-c63d-47c1-990f-e8e7ff005186.png)[](https://user-images.githubusercontent.com/33069673/157725210-4cd05d46-f26e-4c04-9a7e-2f37c742c44b.png)[](https://user-images.githubusercontent.com/33069673/157725243-9af26356-c090-4fb1-aa74-afc90cfde5c3.png) this new beta loses the y-alignment of downbows in our OSMD Function Test - All. Any reasons/thoughts?
image

before:
image

after:
image

I'll still merge this new beta anyways because this is just a minor downside, though it would be nice to keep the y-alignment.

The fixes for extra clefs and beams are very nice!

About the osmd beta with vexflow 4, we can do that, though that's also time that could be spent on other things, and I'm not sure we want to make 10 betas for vexflow 4 with each update. Let's see. You should be able to just build it yourself from this branch for now.

**Comment by rvilarl** [comment]
Having a beta would provide feedback from other people. @infojunkie is the build it yourself approach good for you?

**Comment by infojunkie** [comment]
Sure, I routinely build the library to test out different fixes and branches.

**Pull request merged**
