### PR TITLE
Add option to read measure numbers from musicxml measure attribute

### PR DESCRIPTION
**Pull request by jmorag**
Implements https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/541

### CODE REVIEW

**Comment by sschmidTU** [comment]
Good idea, thanks for the implementation!

However, we currently use the measure number for some array indexes and comparisons. The easiest option is probably to save the printed measure number as an extra variable.
It makes sense to save both anyways, because you may want to start your printed measure numbers at something other than 1, but logically a sheet always has a linear sequence of measures, where we can use 0 as an array index for the first measure.

Adding the printed measure number as an extra variable in SourceMeasure is easy, i'll do that, after merging this to a feature branch.

**Comment by sschmidTU** [comment]
@jmorag by the way, do you have a nice small MusicXML sample with modified measure numbers?

**Comment by sschmidTU** [comment]
This is now merged to develop, see #541.

**Comment by jmorag** [comment]
> @jmorag by the way, do you have a nice small MusicXML sample with modified measure numbers you can share?

Sure, here it is. 
[Prokofiev_violin_concerto_No_2_excerpt.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5177006/Prokofiev_violin_concerto_No_2_excerpt.txt)

Thanks for improving my implementation. The non-linear numbering is pretty cool. I just hope I never encounter any music that needs it :-D

**Comment by sschmidTU** [comment]
Thanks for the sample! Looks good to me.
image

Yes, i'm not sure there is a valid use case for nonlinear measure numbering, but supporting it is easier than not to ;)

**Pull request merged**
