### PR TITLE
Migration/vexflow4.0webpack5.0

### PR DESCRIPTION
**Pull request by rvilarl**
Webpack 5.0

Trying to resolve Vex.Flow. removal issue with webpack 5.0

### CODE REVIEW

**Comment by sschmidTU** [comment]
Just making a note: Will be reviewed/merged after the vexflow 4.0 without package changes is merged.

**Comment by rvilarl** [comment]
> Just making a note: Will be reviewed/merged after PR #1089 (with vexflow 4.0 but without package changes) is merged.

Hi Simon, it is a trial to resolve the Vex.Flow. prefix. I have tried everything that @ronyeh and I could think about and we had the idea that perhaps it was due to the old packages, we will see :)

**Comment by sschmidTU** [comment]
@rvilarl not sure what the exact problem is right now, but have you tried looking at `.appveyor.yml`? It's still using node 12, so you could try node 16 (current LTS).

**Comment by rvilarl** [comment]
Wow! Checks passed! 
I will also look into the node topic, thanks Simon!

**Comment by rvilarl** [comment]
What I am trying to resolve is to remove the Vex.Flow. this has not been possible without updating the packages.🙂

**Comment by rvilarl** [comment]
@sschmidTU the node 16 also does not solve the problem of process indefinition with webpack 5 :( This is an issue to be resolved. And something funny because it fails on the CI environment but not run locally.

**Comment by rvilarl** [comment]
Ready to review, all Vex.Flow. removed.

**Comment by sschmidTU** [comment]
@rvilarl just change the `drawableBoundingBoxElement` string to "None" instead of "false", as i mentioned in the review comment above.

**Comment by rvilarl** [comment]
> @rvilarl just change the `drawableBoundingBoxElement` string to "None" instead of "false", as i mentioned in the review comment above. It should have the same effect, but "false" is not a correct value. We check for certain values, one of them being "None".

Done

**Pull request closed without merging**
