### PR TITLE
Demo: Add Rerender button, add column to layout

### PR DESCRIPTION
**Pull request by sschmidTU**
Adds a rerender button to our demo, which is useful for debugging, see #360.
It behaves like the zoom button, just without the zoom.

I added a column to the layout, otherwise there would have been three rows.

I can still change the layout if there are objections.

image

Just by trying out the button, i discovered that the first rerender of a piece can effectively shrink or stretch the layout, which i didn't expect.

### CODE REVIEW

**Comment by bneumann** [comment]
I would like to object. Why is that really needed on the demo page? What's different to console render() ?

**Comment by sschmidTU** [comment]
The difference is that it's easier and more obvious for developers who don't know the console command, and window.osmd.render() doesn't work for me, as i wrote in #360.

The demo page is only for development anyways, this will probably not be included in our [official demo](https://opensheetmusicdisplay.org/demo/).

**Comment by sschmidTU** [comment]
By the way, you can't open or resize the Chrome Developer Tools without triggering a resize and rerender, and they always take away from the main window's width.

**Comment by bneumann** [comment]
Okay you're right. If you open the dev tools in an extra window it won't trigger anything even if you open them.

**Comment by sschmidTU** [comment]
@bneumann by the way, how do you trigger a rerender in the console? window.osmd.render() doesn't work for me, just returns undefined, though without the () it returns the right function.

Still, i think a good debugging environment is important for development, and right now that's our demo. We could make a separate debugging environment and add overhaul our demo and everything, but for now i'd love to include this for debugging. Writing or copy-pasting something into the Chrome console every time is not very convenient.

**Comment by bneumann** [comment]
I actually never tried just the render function. But the drawBoundingBoxes function also calls render. So I wonder why it wouldn't work.
Instead of copy you can also use arrow up. The history is saved over sessions

**Comment by sebastianhaas** [comment]
Can't really comment on the issue, but a small suggestion: Maybe we want to change the button to re-render, redraw or refresh. Took me a while to actually get the rerender in the first place. I also did some online and offline research.

Three col layout is fine by me, Angular/WP etc. plugins would be highly appreciated. I hope I will find time to do it at some point. (#106, #25)

Sry and out. 🌷

**Comment by bneumann** [comment]
Lgtm I'd say

**Comment by sschmidTU** [comment]
Yes, i'm all for merging this. I thought there was still some dispute about the layout.
I would just change the button to say "re-render" instead of "rerender". "Rerender" is clear to me, but apparently it causes confusion.

**Comment by sebastianhaas** [comment]
shall we publish a minor on npm, so that the demo gets updated on the website?

**Comment by sschmidTU** [comment]
Just for the re-render button that's not necessary I think. It's more useful for debugging.
But we could make a new minor npm and Github release soon with some of the error handling and little other improvements

**Pull request merged**
