### PR TITLE
Added more tempo-related expressions

### PR DESCRIPTION
**Pull request by fablau**
Added more tempo-related expressions for consistency as discussed on issue #1347

### CODE REVIEW

**Comment by sschmidTU** [comment]
Looks good to me, merging.

visual diffs:
[diff_tempo_expressions_added_pr1361.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11548070/diff_tempo_expressions_added_pr1361.zip)

In the diffs, this just adds `ritard.` for 2 samples, Dichterliebe and Haydn Concertante, which is nice.
image

image

image

Note that expressions like `dim. ---` and I think `rall. ---` are not yet implemented with the long dashes interval, see #345.

Also, sorry for the delay in merging!

**Comment by sschmidTU** [comment]
@fablau There is a small merge conflict now, could you fix it?
This docstring should go over the NewPage EngravingRule:
`Whether to begin a new page ("page break")...`

**Comment by fablau** [comment]
Thanks Simon, no worries! Please, check and see if it is now correct.

**Comment by sschmidTU** [comment]
@fablau Did you push your merge? I see no new commits and Github still shows the merge conflict in this PR.
The branch is https://github.com/fablau/opensheetmusicdisplay/tree/improvement/moreTempoExpressions

**Comment by fablau** [comment]
I am sorry Simon, please, try again. I also added this line in package.json:

` "opensheetmusicdisplay": "file:opensheetmusicdisplay.min.js"`

Please, let me know if you want me to remove that as well. I added it for my local testing environment, but I am not sure if that conflicts with the rest in some way.

Thanks!

Fab.

**Comment by sschmidTU** [comment]
@fablau unfortunately yes, please remove that, because osmd doesn't need osmd as a dependency ;)

**Comment by fablau** [comment]
Done!

**Comment by sschmidTU** [comment]
Great, now merging for real ;)
thanks again!

**Comment by fablau** [comment]
Wonderful! More will come!

**Pull request merged**
