### PR TITLE
Feat/vexflow 4.0.1

### PR DESCRIPTION
**Pull request by rvilarl**
Vexflow updated to release 4.0.1.
Merged changes from develop.

@sschmidTU @infojunkie it would be very nice to get your feedback for the next vexflow bug release 4.0.2 or next release 4.1.0

### CODE REVIEW

**Comment by infojunkie** [comment]
@rvilarl happy to help, but can you explain more what kind of feedback you are expecting?

**Comment by rvilarl** [comment]
What are the show stoppers to get it merged im order to resolve them? I really want to get vexflow 4 integrated in OSMD

**Comment by rvilarl** [comment]
I know #1139 some issues there are resolved with vexflow 4.0.1 in this PR. Perhaps the easiest is:
- to merge this PR
- to reevaluate the status of the problems  #1139
- to let me know if any of the open issues are "must do" so that I resolve them in 4.0.2
- finally to merge

**Comment by rvilarl** [comment]
Pianoplay is now online using this branch with Vexflow 4.0.1
https://michaelecke.com/pianoplay

**Comment by sschmidTU** [comment]
@rvilarl There are a few new problems in Vexflow 4.0.1.

- [ ] In OSMD Function Test - Invisible Notes, rests disappear:
(diff:)
image

I assume something goes wrong when unifying visible and invisible rests (Musescore:):
image

Also, the half rest in measure 5 is missing now:
image

- [ ] Often the last notes in a measure are way too far from the measure line (except for rare cases):
before:
image

after:
image

(`test_rest_positioning_note_overlap_1st_voice_chord.musicxml`)

before:
image

after:
image

(OSMD Function Test - Chord Symbols. Also in OSMD Function Test - Color, etc)

one case where this is interestingly better (closer) than before:
before:
image

after:
image
(Land der Berge, measure 13)

also Christbaum measure 6 (better than before):
before:
image

after:
image

-----

A nice improvement on the other hand that should be mentioned is rest unification in some cases :)
image

image

image
(test notehead sharing eighth + quarter)

**Comment by sschmidTU** [comment]
By the way, to get the diffs, you might have to delete the `^` signs in the package.json, because it means "compatible with", and sometimes doesn't install the correct version when running npm install (e.g. from 4.0.1-beta to 4.0.1).

Full diffs:
[diff_vexflow4.01_from_4.01-beta.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/8373730/diff_vexflow4.01_from_4.01-beta.zip)

**Comment by sschmidTU** [comment]
@rvilarl If you agree, I'll merge this for now, but I'll add the issues above to the issue list in https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1139#issuecomment-1032827943 and mention that they were introduced in 4.0.1 (after the beta).
(also, thanks for merging develop)

**Comment by rvilarl** [comment]
> @rvilarl If you agree, I'll merge this for now, but I'll add the issues above to the issue list in [#1139 (comment)](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1139#issuecomment-1032827943) and mention that they were introduced in 4.0.1 (after the beta). (also, thanks for merging develop)

please go ahead

**Pull request merged**
