### PR TITLE
Adding Slides, Bends, Hammer-on and Pull-offs

### PR DESCRIPTION
**Pull request by momolarson**

### CODE REVIEW

**Comment by momolarson** [comment]
let me know how you'd like me to change it

**Comment by sschmidTU** [comment]
@momolarson hey, your changes are merged to develop now.
Can you maybe add some samples with these features (slides, bends, etc) here for testing? Or at least screenshots? That would be great.
Thanks again for the contributions!

**Comment by momolarson** [comment]
will do Simon!  I assume samples would work with the demo app? Where would you like me to document this?

**Comment by sschmidTU** [comment]
Yes, samples should work with the demo app.
Adding the samples in issue #814 would be best i think. It can be one big zip.

**Pull request merged**
