### PR TITLE
Fix bug when endingIndices are undefined. Only add space for title on…

### PR DESCRIPTION
**Pull request by LearnedLately**
… first page.

### CODE REVIEW

**Comment by bneumann** [comment]
Hi, thank you for the fix. Can you enlighten me a bit about the bug it fixes? Code looks fine to me

**Comment by LearnedLately** [comment]
Hi, yeah, apparently sometimes endingIndices are undefined, but the code checks for the 'length' property, causing an error. I noticed this when I made another change that created multiple pages.

**Comment by matt-uib** [comment]
@LearnedLately, thanks very much for the investigation and the fix! The change in the calculator makes totally sense! For now we didn't really use the pages, as a page has currently a very large height and therefore only one is produced as all fits on it.
For the repetition fix: yes this is of course needed, thanks! i just think of one more thing that might be useful. Can you add a check that the two lengths are equal (if the arrays exist) so that the last check won't fail with a possible index-out-of-bounds error? That would be great and then we merge it :-)

**Comment by sebastianhaas** [comment]
Changes were incorporated in 9c7e164

**Pull request closed without merging**
