### PR TITLE
Generate ottava over multiple stafflines (#591)

### PR DESCRIPTION
**Pull request by fredmeister77**
Fix issue with ottava's only being generated on start and end staffline.
Further fixes for sky/bottom line generation

Visual Regression Test Results:
[visual_results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4739940/visual_results.txt)

Test Results:
[test_results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4739941/test_results.txt)

### CODE REVIEW

**Comment by sschmidTU** [comment]
octave multiline sample collection:
[octave_multiline_samples.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4746281/octave_multiline_samples.zip)

the sample titled 48 has a few superfluous ottavas. Maybe we can merge these?
image

-----

The allegretto sample doesn't seem to render an ottava over two lines correctly.
@fredmeister77 this second issue seems more important, do you have an idea what could be the problem here?
one one line it renders the full ottava:
image

but not if it starts at the end of the previous staffline:
image

sample:
[octave_allegretto_sample_bar13_to_16.musicxml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4746273/octave_allegretto_sample_bar13_to_16.musicxml.txt)

**Comment by fredmeister77** [comment]
Thanks,
Still on my list :) 
Have had other things take priority so far

**Comment by fredmeister77** [comment]
This is finally fixed. @sschmidTU, let me know if you find any additional problems with it.
Visual results:
[visual_results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5395567/visual_results.txt)
Test Results:
[test_results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5395568/test_results.txt)

**Comment by sschmidTU** [comment]
Looks good! Ottavas over multiple lines are fixed. Merging.

Multiline sample:
(https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5467801/8va_many_lines.musicxml.zip)
(see #591 for screenshots)
In this sample we need to disable auto-generating multirests:
```js
osmd.setOptions({autoGenerateMutipleRestMeasuresFromRestMeasures: false})
```
Maybe we should disable that option by default, MuseScore doesn't multirest by default either.

**Pull request merged**
