### PR TITLE
Fix/ajax timeout

### PR DESCRIPTION
**Pull request by bneumann**

### CODE REVIEW

**Comment by sschmidTU** [comment]
LGTM.
What is IE? Internet Explorer?
I assume you tested that part.

**Comment by bneumann** [comment]
No I didn't, am not mad and install IE on my pristine system. 😁 But I read the docs for http requests and in a footnote was mentioned that you should support timeouts as well.

**Comment by sschmidTU** [comment]
You might have tested IE on a VM with Windows XP for "legacy" support ;)

**Comment by bneumann** [comment]
True I still have one somewhere. But it's a little change anyways

**Pull request merged**
