### PR TITLE
Added a reference to `GraphicalNote` from `Note`

### PR DESCRIPTION
**Pull request by praisethemoon**
Hello!

I believe that this tiny change would really prove usefull as it is strongly related to https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/549 in the sense that it would be easier to get the graphical note object from, for example cursor using`osmd.cursor.iterator.currentVoiceEntries[0].notes[0].graphicalNote.getSVGGElement().id` which is more convinient than fetching it from `osmd.GraphicSheet.MeasureList[0][0].staffEntries[0].graphicalVoiceEntries[0].notes[0]`. If there is something that already exists and solves this problem, please let me know!

For me this is the best way to hack into the low-level SVG generated objects to change their style, and I do hope you find it useful!

Cheers!

### CODE REVIEW

**Comment by sschmidTU** [comment]
Hey, i basically answered this in a new issue in #660.
The thing is, we wanted to avoid creating references to graphical classes in sheet model classes, to modularize OSMD and make it possible to use the sheet model without the graphics classes.
It should be almost as easy with the solution in #660 though. We can also add a static method to Cursor or GraphicalNote that gets you the GraphicalNote from a Note via the new dictionary.

**Comment by Jack-Works** [comment]
How does this PR going? 👀

**Comment by sschmidTU** [comment]
@Jack-Works As i said, we do not want a direct reference to graphical classes in our sheet model classes, but hopefully #659 will get resolved and then you will have a way to find a GraphicalNote from a Note that is almost as easy as a reference in Note.

**Comment by ice6** [comment]
@praisethemoon this is a great feature, when you design an interactive sheet music app.

@sschmidTU this library is a bridge layer between `musicxml` and `vexflow`, it is inevitable that you have to interact with the ui layer(vexflow). 

Maybe we can add a `GraphicalNote ` property to `Note.ts` with datatype `any`, if you don't want to make a circular dependency. 

With @praisethemoon 's change, we can access HTML element from the note data happily like this.

`osmd.cursor.iterator.currentVoiceEntries[0].notes[0].graphicalNote.vfnote[0].attrs.el`

If we dig the code deeper, I think there is no reason for `AJAX.ts` existing in this library. 😄

**Comment by ice6** [comment]
@sschmidTU 

After rethinking, maybe we just need to add a `currentGraphicalNotes` attribute to `osmd.cursor.iterator`.

This can solve many ui interaction problems.

**Comment by matt-uib** [comment]
@ice6 thanks for your comments here also.
Our idea is to keep the general objectmodel built up from musicxml and also the cursor clean from the final graphical implementations. An Idea is for example: a musicxml audio player without even rendering any notes.
Our solution would be the dict described in #660 . Would you see any problems with this approach?

**Comment by ice6** [comment]
After more digging, I found that `osmd.cursor.iterator.currentMeasure.verticalMeasureList[0].staffEntries[0].graphicalVoiceEntries[0].notes[0].vfnote[0].attrs.el`, this already can solve many ui interaction requirements.

@matt-uib it is ok to use dictionary to solve the problem. and the final api is clean. If it is already implemented, I would not discuss here. :P

**Comment by sschmidTU** [comment]
> If we dig the code deeper, I think there is no reason for `AJAX.ts` existing in this library. 😄

@ice6  AJAX is used in OpenSheetMusicDisplay.ts to retrieve a MusicXML file asynchronously from a website.

**Comment by ice6** [comment]
> > If we dig the code deeper, I think there is no reason for `AJAX.ts` existing in this library. 😄
> 
> @ice6 AJAX is used in OpenSheetMusicDisplay.ts:load() to retrieve a MusicXML file asynchronously from a website.

@sschmidTU sure, I know. just from the architecture perspective.

below is the code I use to retrieve file by url, it provides more flexibility some time.

```
let res = await fetch(url)
let content = await res.text()
```

**Comment by sschmidTU** [comment]
There is now the static `GraphicalNote.FromNote(note: Note, rules: EngravingRules)`,
so you can easily get the GraphicalNote like this:
`const gNote = GraphicalNote.FromNote(note, osmd.rules);`

See #660.

**Comment by sschmidTU** [comment]
There is an even easier method now:
`const gNote = osmd.rules.GNote(note)`
will give you the GraphicalNote from a Note reference.

**Pull request closed without merging**
